---
- name: Setup Projector Controller
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Create /root/apps directory
      file:
        path: /root/apps
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Upload docker-compose.yml file
      template: 
        src: docker-compose.yml.j2
        dest: /root/apps/docker-compose.yml
        owner: root
        group: root
        mode: 0600

    - name: Login to private Docker registry
      docker_login:
        registry: registry.potatolab.dev
        username: "{{ lookup('env', 'HOME_REGISTRY_USERNAME') }}"
        password: "{{ lookup('env', 'HOME_REGISTRY_PASSWORD') }}"

    - name: Create & run docker containers
      shell: 
        cmd: docker compose up -d
        chdir: /root/apps

    - name: Get output of docker compose ps
      shell: 
        cmd: docker compose ps --format json
        chdir: /root/apps
      register: output

    - name: Show docker compose ps output
      ansible.builtin.debug:
        var: output
